name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t devops-demo ./app

      - name: Tag image
        run: |
          docker tag devops-demo:latest 869935080468.dkr.ecr.ap-southeast-2.amazonaws.com/devops-demolucas:latest

      - name: Push to ECR
        run: |
          docker push 869935080468.dkr.ecr.ap-southeast-2.amazonaws.com/devops-demolucas:latest